[package]
name = "example"
version = "0.1.0"
edition = "2021"

# For Windows
#linker = "x86_64-w64-mingw32-gcc"

# For Linux
linker = "x86_64-unknown-linux-gnu-gcc"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
